package de.benjaminborbe.analytics.api;

import java.util.Collection;
import java.util.List;

import de.benjaminborbe.api.ValidationException;
import de.benjaminborbe.authentication.api.LoginRequiredException;
import de.benjaminborbe.authentication.api.SessionIdentifier;
import de.benjaminborbe.authorization.api.PermissionDeniedException;

public interface AnalyticsService {

	String ANALYTICS_ROLE_ADMIN = "AnalyticsAdmin";

	String ANALYTICS_ROLE_VIEW = "AnalyticsView";

	void addReportValue(AnalyticsReportIdentifier analyticsReportIdentifier) throws AnalyticsServiceException;

	void addReportValue(AnalyticsReportIdentifier analyticsReportIdentifier, AnalyticsReportValue reportValue) throws AnalyticsServiceException;

	void addReportValue(AnalyticsReportIdentifier analyticsReportIdentifier, double value) throws AnalyticsServiceException;

	void addReportValue(AnalyticsReportIdentifier analyticsReportIdentifier, long time) throws AnalyticsServiceException;

	void aggreate(SessionIdentifier sessionIdentifier) throws AnalyticsServiceException, PermissionDeniedException, LoginRequiredException;

	AnalyticsReportIdentifier createAnalyticsReportIdentifier(String id) throws AnalyticsServiceException;

	void createReport(SessionIdentifier sessionIdentifier, AnalyticsReportDto report) throws AnalyticsServiceException, PermissionDeniedException, LoginRequiredException,
			ValidationException;

	void deleteReport(SessionIdentifier sessionIdentifier, AnalyticsReportIdentifier analyticsIdentifier) throws AnalyticsServiceException, PermissionDeniedException,
			LoginRequiredException;

	void expectAnalyticsAdminRole(SessionIdentifier sessionIdentifier) throws PermissionDeniedException, LoginRequiredException, AnalyticsServiceException;

	void expectAnalyticsViewOrAdminRole(SessionIdentifier sessionIdentifier) throws PermissionDeniedException, LoginRequiredException, AnalyticsServiceException;

	void expectAnalyticsViewRole(SessionIdentifier sessionIdentifier) throws PermissionDeniedException, LoginRequiredException, AnalyticsServiceException;

	Collection<String> getLogWithoutReport(SessionIdentifier sessionIdentifier) throws AnalyticsServiceException, PermissionDeniedException, LoginRequiredException;

	AnalyticsReportValueIterator getReportIterator(SessionIdentifier sessionIdentifier, AnalyticsReportIdentifier analyticsReportIdentifier,
			AnalyticsReportInterval analyticsReportInterval) throws AnalyticsServiceException, PermissionDeniedException, LoginRequiredException;

	AnalyticsReportValueIterator getReportIteratorFillMissing(SessionIdentifier sessionIdentifier, AnalyticsReportIdentifier analyticsReportIdentifier,
			AnalyticsReportInterval analyticsReportInterval) throws AnalyticsServiceException, PermissionDeniedException, LoginRequiredException;

	AnalyticsReportValueListIterator getReportListIterator(SessionIdentifier sessionIdentifier, List<AnalyticsReportIdentifier> analyticsReportIdentifiers,
			AnalyticsReportInterval analyticsReportInterval) throws AnalyticsServiceException, PermissionDeniedException, LoginRequiredException;

	AnalyticsReportValueListIterator getReportListIteratorFillMissing(SessionIdentifier sessionIdentifier, List<AnalyticsReportIdentifier> analyticsReportIdentifiers,
			AnalyticsReportInterval analyticsReportInterval) throws AnalyticsServiceException, PermissionDeniedException, LoginRequiredException;

	Collection<AnalyticsReport> getReports(SessionIdentifier sessionIdentifier) throws AnalyticsServiceException, PermissionDeniedException, LoginRequiredException;

	boolean hasAnalyticsAdminRole(SessionIdentifier sessionIdentifier) throws LoginRequiredException, AnalyticsServiceException;

	boolean hasAnalyticsViewOrAdminRole(SessionIdentifier sessionIdentifier) throws LoginRequiredException, AnalyticsServiceException;

	boolean hasAnalyticsViewRole(SessionIdentifier sessionIdentifier) throws LoginRequiredException, AnalyticsServiceException;

	void rebuildReport(SessionIdentifier sessionIdentifier, AnalyticsReportIdentifier analyticsReportIdentifier) throws AnalyticsServiceException, PermissionDeniedException,
			LoginRequiredException;

	void rebuildReports(SessionIdentifier sessionIdentifier) throws AnalyticsServiceException, PermissionDeniedException, LoginRequiredException;
}
