package de.benjaminborbe.filestorage.api;

import de.benjaminborbe.api.ValidationException;

public interface FilestorageService {

	FilestorageEntryIdentifier createFilestorageEntryIdentifier(String id) throws FilestorageServiceException;

	FilestorageEntryIdentifier createFilestorageEntry(FilestorageEntry filestorageEntry) throws FilestorageServiceException, ValidationException;

	FilestorageEntry getFilestorageEntry(FilestorageEntryIdentifier filestorageEntryIdentifier) throws FilestorageServiceException;

	void deleteFilestorageEntry(FilestorageEntryIdentifier filestorageEntryIdentifier) throws FilestorageServiceException;
}
