all:
	mvn -Djava.awt.headless=true install
installwotest:
	mvn -Djava.awt.headless=true -Dmaven.test.skip=true install
dir:
	mkdir -p src/main/resources src/main/java src/test/resources src/test/java
